=== suiyueliushang/xml-code/xml_3/Animation_3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<!-- 简易元素的定义 -->
<xs:element name="animeName" type="xs:string"/>
<xs:element name="platform" type="platform-list"/>
<xs:element name="src" type="xs:string"/>
<xs:element name="vv" type="xs:nonNegativeInteger" nillable="true"/>
<xs:element name="comment" type="xs:string"/>
<xs:simpleType name="people-list">
    <xs:list itemType="xs:Name"/>
</xs:simpleType>
<!-- 属性的定义-->
<xs:attribute name="id" type="xs:string"/>
<!-- 符合元素的定义-->
<xs:complexType name="score-scope">
    <xs:simpleContent>
        <xs:extension base="xs:decimal">
            <xs:attribute type="platform-list" name="platform" use="required"/>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>

<xs:simpleType name="platform-list">
    <xs:restriction base="xs:string">
        <xs:enumeration value="腾讯视频"/>
        <xs:enumeration value="优酷网"/>
        <xs:enumeration value="土豆网"/>
        <xs:enumeration value="bilibili"/>
        <xs:enumeration value="爱奇艺"/>
        <xs:enumeration value="youtube"/>
        <xs:enumeration value="人人影视"/>
        <xs:enumeration value="搜狐视频"/>
        <xs:enumeration value="乐视网"/>
        <xs:enumeration value="pptv"/>
        <xs:enumeration value="豆瓣"/>
    </xs:restriction>
</xs:simpleType>

<xs:element name="detail">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="animeMaker" type="xs:string"/>
            <xs:element name="director" type="people-list"/>
            <xs:element name="screenwriter" type="people-list"/>
            <xs:element name="posterSrc" type="xs:string"/>
            <xs:element name="releasePlace" type="xs:string"/>
            <xs:element name="language" type="xs:string"/>
            <xs:element name='duration' >
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:nonNegativeInteger">
                            <xs:attribute name="units" type="xs:string" default="minute" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="totalEpisodes" type="xs:integer"/>
            <xs:element name="type">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="label" minOccurs="0" maxOccurs="unbounded">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="剧情"/>
                                    <xs:enumeration value="玄幻"/>
                                    <xs:enumeration value="武侠"/>
                                    <xs:enumeration value="科幻"/>
                                    <xs:enumeration value="历史"/>
                                    <xs:enumeration value="冒险"/>
                                    <xs:enumeration value="言情"/>
                                    <xs:enumeration value="萌宠"/>
                                    <xs:enumeration value="末日"/>
                                    <xs:enumeration value="战争"/>
                                    <xs:enumeration value="恐怖"/>
                                    <xs:enumeration value="动漫改"/>
                                    <xs:enumeration value="热血"/>
                                    <xs:enumeration value="声控"/>
                                    <xs:enumeration value="战斗"/>
                                    <xs:enumeration value="恋爱"/>
                                    <xs:enumeration value="校园"/>
                                    <xs:enumeration value="智斗"/>
                                    <xs:enumeration value="日常"/>
                                    <xs:enumeration value="悬疑"/>
                                    <xs:enumeration value="推理"/>
                                    <xs:enumeration value="搞笑"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="form"  use="optional" default="2D">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="2D"/>
                                <xs:enumeration value="3D"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:complexType>
            </xs:element>
            <xs:element name="score" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:restriction base="score-scope">
                            <xs:fractionDigits value="1"/>
                            <xs:maxInclusive value="10.0"/>
                            <xs:minExclusive value="0.0" />
                        </xs:restriction>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="startTime" type="xs:date"/>
            <xs:element name="endTime" type="xs:date" nillable="true"/>
            <xs:element name="animeIntroduction" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:element name="resource">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="platform"/>
            <xs:element ref="src"/>
            <xs:element ref="vv" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:element name="animation">
 <xs:complexType>
  <xs:sequence>
   <xs:element ref="animeName"/>
   <xs:element ref="detail"/>
   <xs:element ref="resource" maxOccurs="unbounded"/>
   <xs:element ref="comment"/>
  </xs:sequence>
  <xs:attribute ref="id" use="required"/>
 </xs:complexType>
</xs:element>
<xs:element name="animation-list">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="animation" minOccurs="15" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== suiyueliushang/xml-code/xml_3/Animation_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Animation_3.xsl"?>
<!--teamid=13 team="一直自闭" version=3.0-->
<animation-list xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
xsd:noNamespaceSchemaLocation="Animation_3.xsd">
	<animation id="A001">
		<animeName>
			秦时明月之百步飞剑
		</animeName>
		<detail>
			<animeMaker>
				杭州玄机科技信息有限公司
			</animeMaker>
			<director>
				沈乐平
			</director>
			<screenwriter>
				沈乐平 
			</screenwriter>
			<posterSrc>
				<![CDATA[ https://puui.qpic.cn/vcover_vt_pic/0/sdp00100517th901576489903/0]]>
			</posterSrc>
			<releasePlace>
				中国
			</releasePlace>
			<language>
				汉语
			</language>
			<duration units="minute">
				22
			</duration>
			<totalEpisodes>
				20
			</totalEpisodes>
			<type form="3D">
				<label>剧情</label>
				<label>冒险</label>
				<label>武侠</label>
				<label>历史</label>
			</type>
			<score platform="腾讯视频">
				7.6
			</score>
			<score platform="土豆网">
				8.8
			</score>
			<score platform="优酷网">
				8.8
			</score>
			<score platform="爱奇艺">
				8.7
			</score>
			<startTime>
				2007-02-14
			</startTime>
			<endTime>
				2008-06-10
			</endTime>
			<animeIntroduction>
				<![CDATA[ 《秦时明月之百步飞剑》以秦始皇灭六国为时代背景，讲述了剑圣盖聂携荆轲之子荆天明为躲避秦王追杀，踏上了风起云涌的荆棘之途。逃亡路上，盖聂、天明结识了墨家众高手、楚国大将之后项少羽和谜样少女高月，一行人在命运的引领下进入被誉为世间最后一片净土的墨家机关城。]]>
			</animeIntroduction>
		</detail>
		<resource>
			<platform><![CDATA[腾讯视频]]></platform>
			<src>
				https://v.qq.com/x/page/h0033i56bl1.html
			</src>
			<vv>
				56368000
			</vv>
		</resource>
		<resource>
			<platform>土豆网</platform>
			<src>
				<![CDATA[https://www.soku.com/detail/show/XODYyMDIw?spm=a2h0k.8191414.big_word_ul_3.3~A&siteId=1]]>
			</src>
			<vv>
				223409029
			</vv>
		</resource>
		<resource>
			<platform>优酷网</platform>
			<src>
				<![CDATA[https://v.youku.com/v_show/id_XMTcyNzY2OTg0.html?spm=a2h0k.11417342.soresults.dposter]]>
			</src>
		</resource>
		<resource>
			<platform>爱奇艺</platform>
			<src>
				<![CDATA[http://www.iqiyi.com/v_19rrjdtc64.html]]>
			</src>
		</resource>
		<comment>
			<![CDATA[ 
			江湖儿女，快意恩仇，秦时有。
			
			王侯将相，诸子百家，秦时有。
			
			礼乐书数，博弈论道，秦时有。
			
			建模也好，特效也好。]]>
		</comment>
	</animation>

	<animation id="A002">
		<animeName>
			秦时明月之夜尽天明
		</animeName>
		<detail>
			<animeMaker>
				杭州玄机科技信息有限公司
			</animeMaker>
			<director>
				沈乐平 
			</director>
			<screenwriter>
				沈乐平
			</screenwriter>
			<posterSrc>
				<![CDATA[https://puui.qpic.cn/vcover_vt_pic/0/sdp001x16cyw34a1544510189/0]]>
			</posterSrc>
			<releasePlace>
				中国
			</releasePlace>
			<language>
				汉语
			</language>
			<duration units="minute">
				22
			</duration>
			<totalEpisodes>
				18
			</totalEpisodes>
			<type form="3D">
				<label>剧情</label>
				<label>冒险</label>
				<label>武侠</label>
				<label>历史</label>
			</type>
			<score platform="豆瓣">
				9.1
			</score>
			<score platform="腾讯视频">
				7.6
			</score>
			<score platform="土豆网">
				9.3
			</score>
			<score platform="优酷网">
				9.3
			</score>
			<startTime>
				2008-07-17
			</startTime>
			<endTime>
				2009-12-11
			</endTime>
			<animeIntroduction>
				<![CDATA[ 开篇便是大铁锤与隐蝠的激战，之后便是高渐离与雪女联手战胜了隐蝠，隐蝠败走。而此时，卫庄的手下黑麒麟已经化妆成大铁锤手下潜入墨家机关城。黑麒麟打伤班大师，夺得机关城内部构造图交给卫庄，卫庄命令黑麒麟在机关城核心的中心水池下毒，之后，黑麒麟易容成盖聂暗算徐夫子，不但下毒成功，而且使得高渐离对盖聂生疑，将其软禁在房间内。]]>
			</animeIntroduction>
		</detail>
		<resource>
			<platform>腾讯视频</platform>
			<src>
				<![CDATA[ https://v.qq.com/x/page/h0033lwsz5l.html]]>
			</src>
			<vv>
				56368000
			</vv>
		</resource>
		<resource>
			<platform>优酷网</platform>
			<src>
				<![CDATA[https://v.youku.com/v_show/id_XMTA1NjA4ODQ0.html?spm=a2h0k.11417342.soresults.dposter]]>
			</src>
		</resource>
		<resource>
			<platform>土豆网</platform>
			<src>
				<![CDATA[https://www.soku.com/detail/show/XMjI0NTQw?spm=a2h0k.8191414.big_word_ul_8.3~A&siteId=1]]>
			</src>
			<vv>
				224263888
			</vv>
		</resource>
		<comment>
			<![CDATA[ 这一部长达百集的系列动漫连续剧。故事取材于秦始皇灭六国到西楚霸王项羽攻陷咸阳这一英雄辈出的历史时期，此后数年间，各种历史传说纷呈迭起，诸子百家也伴随着历史风云横空出世，筑就了一部气势恢宏的故国群英图。少年荆天明如旷野杂草顽强地生长在时代变革的乱世之秋，剑客高渐离、盖聂，隐士墨家及众多豪杰仰天长啸于古华夏天宇。秦始皇、项羽，这些纵横捭阖的旷世英雄和历史人物在一出场时，就给了观众更具时代感的张力表现和视觉冲击。随之而来的诸子百家文化悉数登场：墨家、儒家、法家、道家、兵家、农家、纵横家等等]]>
		</comment>
	</animation>

	<animation id="A003">
		<animeName>
			秦时明月之诸子百家
		</animeName>
		<detail>
			<animeMaker>
				杭州玄机科技信息有限公司
			</animeMaker>
			<director>
				沈乐平
			</director>
			<screenwriter>
				沈乐平
			</screenwriter>
			<posterSrc>
				<![CDATA[ https://puui.qpic.cn/vcover_vt_pic/0/sdp0010051b4zwj1576237226/0]]>
			</posterSrc>
			<releasePlace>
				中国
			</releasePlace>
			<language>
				汉语
			</language>
			<duration units="minute">
				22
			</duration>
			<totalEpisodes>
				34
			</totalEpisodes>
			<type form="3D">
				<label>剧情</label>
				<label>冒险</label>
				<label>武侠</label>
				<label>历史</label>
			</type>
			<score platform="腾讯视频">
				7.8
			</score>
			<startTime>
				2010-06-10
			</startTime>
			<endTime>
				2011-12-11
			</endTime>
			<animeIntroduction>
				<![CDATA[ 公元前222年，秦发兵六十万攻楚，楚军节节败退。乱军之中，日后的名将之星蒙恬（蒙武之子）与未来的西楚霸王少羽第一次在沙场相遇。
				楚军寡不敌众，情况危急万分，少年霸王与帝国将星的初次交锋，胜负难测……
				两年之后，秦灭六国，统一中国，秦始皇成为中国历史上第一位皇帝。然而，乱世并未结束，一股强大的力量正在为颠覆大秦而崛起。
				墨家、儒家、道家、法家、兵家、纵横家、阴阳家、农家、名家等，历史上称之为诸子百家。他们有的集结六国残余势力，为推翻帝国保证伺机而动；有的追随帝国主人的脚步，希望在这片大地上创立一个宇内光耀千秋万代的辉煌国度；亦有的借帝国的庞大势力，逐步实现自己不为人知的目的……如今，天下反秦势力最后的堡垒——墨家机关城，正遭遇三百年来最大的一次危机……
				盗跖虽然成功脱出，赶往求援，却被一神秘少女拦住去路。与此同时，墨家巨子率领各家英雄在赶往机关城途中，也遭到了阴阳家高手出其不意的暗袭。
				机关城中，身中剑伤的盖聂挥剑斩向身后……
				十年后，纵与横再次交锋，鬼谷的宿命之战，终将在此有一个了结！
				墨家机关城会否就此陷落？墨家众人的命运将何去何从？
				天明的面前究竟还有多少荆棘之路在等待着他？
				被阴阳家虏去的高月又会有何遭遇？
				要以孤家寡人对抗诸子百家，嬴政能有几分胜算？
				在这动荡的乱世中，谁才能成为真正的王者？]]>
			</animeIntroduction>
		</detail>
		<resource>
			<platform>腾讯视频</platform>
			<src>
				https://v.qq.com/x/cover/mzc002001kt6n30.html
			</src>
			<vv>
				20000000
			</vv>
		</resource>
		<resource>
			<platform>腾讯视频</platform>
			<src>
				<![CDATA[https://www.soku.com/detail/show/XODYyMDIw?spm=a2h0k.8191414.big_word_ul_3.3~A&siteId=1]]>
			</src>
			<vv>
				100002232
			</vv>
		</resource>
		<comment>
			<![CDATA[ 秦时明月百步飞剑]]>
		</comment>
	</animation>

	<animation id="A004">
		<animeName>
			秦时明月之万里长城
		</animeName>
		<detail>
			<animeMaker>
				杭州玄机科技信息有限公司
			</animeMaker>
			<director>
				沈乐平 其他人
			</director>
			<screenwriter>
				沈乐平 其他人
			</screenwriter>
			<posterSrc>
				<![CDATA[ https://puui.qpic.cn/vcover_vt_pic/0/mzc002001kt6n301576035032/0]]>
			</posterSrc>
			<releasePlace>
				中国
			</releasePlace>
			<language>
				汉语
			</language>
			<duration units="minute">
				22
			</duration>
			<totalEpisodes>
				20
			</totalEpisodes>
			<type form="3D">
				<label>剧情</label>
				<label>冒险</label>
				<label>武侠</label>
				<label>历史</label>
			</type>
			<score platform="腾讯视频">
				8.9
			</score>
			<startTime>
				2007-02-14
			</startTime>
			<endTime>
				2009-12-11
			</endTime>
			<animeIntroduction>
				<![CDATA[ 《秦时明月之百步飞剑》以秦始皇灭六国为时代背景，讲述了剑圣盖聂携荆轲之子荆天明为躲避秦王追杀，踏上了风起云涌的荆棘之途。逃亡路上，盖聂、天明结识了墨家众高手、楚国大将之后项少羽和谜样少女高月，一行人在命运的引领下进入被誉为世间最后一片净土的墨家机关城。]]>
			</animeIntroduction>
		</detail>
		<resource>
			<platform>腾讯视频</platform>
			<src>
				https://v.qq.com/x/cover/mzc002001kt6n30.html
			</src>
			<vv>
				20000000
			</vv>
		</resource>
		<resource>
			<platform>腾讯视频</platform>
			<src>
				<![CDATA[https://www.soku.com/detail/show/XODYyMDIw?spm=a2h0k.8191414.big_word_ul_3.3~A&siteId=1]]>
			</src>
			<vv>
				100002232
			</vv>
		</resource>
		<comment>
			<![CDATA[ 秦时明月百步飞剑]]>
		</comment>
	</animation>

	<animation id="A005">
		<animeName>
			秦时明月之君临天下
		</animeName>
		<detail>
			<animeMaker>
				杭州玄机科技信息有限公司
			</animeMaker>
			<director>
				沈乐平 其他人
			</director>
			<screenwriter>
				沈乐平 其他人
			</screenwriter>
			<posterSrc>
				<![CDATA[ https://puui.qpic.cn/vcover_vt_pic/0/38nzgv8uwf3zoya1523593501/0]]>
			</posterSrc>
			<releasePlace>
				中国
			</releasePlace>
			<language>
				汉语
			</language>
			<duration units="minute">
				22
			</duration>
			<totalEpisodes>
				20
			</totalEpisodes>
			<type form="3D">
				<label>剧情</label>
				<label>冒险</label>
				<label>武侠</label>
				<label>历史</label>
			</type>
			<score platform="腾讯视频">
				8.9
			</score>
			<startTime>
				2007-02-14
			</startTime>
			<endTime>
				2009-12-11
			</endTime>
			<animeIntroduction>
				<![CDATA[ 《秦时明月之百步飞剑》以秦始皇灭六国为时代背景，讲述了剑圣盖聂携荆轲之子荆天明为躲避秦王追杀，踏上了风起云涌的荆棘之途。逃亡路上，盖聂、天明结识了墨家众高手、楚国大将之后项少羽和谜样少女高月，一行人在命运的引领下进入被誉为世间最后一片净土的墨家机关城。]]>
			</animeIntroduction>
		</detail>
		<resource>
			<platform>腾讯视频</platform>
			<src>
				https://v.qq.com/x/cover/mzc002001kt6n30.html
			</src>
			<vv>
				20000000
			</vv>
		</resource>
		<resource>
			<platform>腾讯视频</platform>
			<src>
				<![CDATA[https://www.soku.com/detail/show/XODYyMDIw?spm=a2h0k.8191414.big_word_ul_3.3~A&siteId=1]]>
			</src>
			<vv>
				100002232
			</vv>
		</resource>
		<comment>
			<![CDATA[ 秦时明月百步飞剑]]>
		</comment>
	</animation>

	<animation id="A006">
		<animeName>
			天行九歌
		</animeName>
		<detail>
			<animeMaker>
				杭州玄机科技信息有限公司
			</animeMaker>
			<director>
				沈乐平 金蕾
			</director>
			<screenwriter>
				沈乐平 
			</screenwriter>
			<posterSrc>
				<![CDATA[ https://puui.qpic.cn/vcover_vt_pic/0/rm3tmmat4li8uul1554835621/0]]>
			</posterSrc>
			<releasePlace>
				中国
			</releasePlace>
			<language>
				汉语
			</language>
			<duration units="minute">
				22
			</duration>
			<totalEpisodes>
				90
			</totalEpisodes>
			<type form="3D">
				<label>剧情</label>
				<label>冒险</label>
				<label>玄幻</label>
				<label>历史</label>
				<label>战斗</label>
			</type>
			<score platform="腾讯视频">
				9.4
			</score>
			<score platform="bilibili">
				9.7
			</score>
			<score platform="爱奇艺">
				8.8
			</score>
			<startTime>
				2016-03-12
			</startTime>
			<endTime>
				2019-12-11
			</endTime>
			<animeIntroduction>
