=== suiyueliushang/xml-code/xml_1/Antimation_1.dtd
<!ELEMENT animation-list (animation*)>
<!ELEMENT animation (animeName,animeMaker,ref,director,screenwriter,origin_author?,releasePlace,language,duration,score*,totalEpisodes,type,startTime,anIntrodu)>
<!ATTLIST animation id ID #REQUIRED>
<!ELEMENT animeName (#PCDATA)>
<!ELEMENT animeMaker (#PCDATA)>
<!ELEMENT ref (#PCDATA)>
<!ATTLIST ref platform CDATA #IMPLIED>
<!ELEMENT director (name*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT screenwriter (name*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT origin_author (name)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT releasePlace (#PCDATA)>
<!ELEMENT language (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ELEMENT score (#PCDATA)>
<!ATTLIST score site CDATA #IMPLIED>
<!ELEMENT totalEpisodes (#PCDATA)>
<!ELEMENT type (label*)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT startTime (year,month,day)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT anIntrodu (#PCDATA)>

=== suiyueliushang/xml-code/xml_1/Animation_1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!--version=2.0 第二个版本-->
<!DOCTYPE animation-list SYSTEM "Antimation_1.dtd">
<animation-list>
    <animation id="A001">
        <animeName>
            秦时明月之百步飞剑
        </animeName>
        <animeMaker>
            杭州玄机科技信息有限公司
        </animeMaker>
        <ref platform="腾讯视频">
            https://v.qq.com/x/cover/mzc002001kt6n30.html
        </ref>
        <director>
            <name>沈乐平</name>
        </director>
        <screenwriter>
            <name>沈乐平</name>
        </screenwriter>
        <origin_author>
            <name>
                温世仁
            </name>
        </origin_author>
        <releasePlace>
            中国
        </releasePlace>
        <language>
            汉语
        </language>
        <duration>
            22分钟/集
        </duration>
        <score site="豆瓣">
            8.9
        </score>
        <totalEpisodes>
            20集
        </totalEpisodes>
        <type>
            <label>剧情</label>
            <label>冒险</label>
            <label>武侠</label>
            <label>历史</label>
        </type>
        <startTime>
            <year>
                2007
            </year>
            <month>
                2
            </month>
            <day>
                14
            </day>
        </startTime>
        <anIntrodu>
            <![CDATA[ 《秦时明月之百步飞剑》以秦始皇灭六国为时代背景，讲述了剑圣盖聂携荆轲之子荆天明为躲避秦王追杀，踏上了风起云涌的荆棘之途。逃亡路上，盖聂、天明结识了墨家众高手、楚国大将之后项少羽和谜样少女高月，一行人在命运的引领下进入被誉为世间最后一片净土的墨家机关城。]]>
        </anIntrodu>
    </animation>

    <animation id="A002">
        <animeName>
            秦时明月之夜尽天明
        </animeName>
        <animeMaker>
            杭州玄机科技信息有限公司
        </animeMaker>
        <ref platform="腾讯视频">
            https://v.qq.com/x/cover/mzc002001kt6n30/h0033lwsz5l.html
        </ref>
        <director>
            <name>沈乐平</name>
        </director>
        <screenwriter>
            <name>沈乐平</name>
        </screenwriter>
        <origin_author>
            <name>
                温世仁
            </name>
        </origin_author>
        <releasePlace>
            中国
        </releasePlace>
        <language>
            汉语
        </language>
        <duration>
            22分钟/集
        </duration>
        <score site="腾讯视频">
            7.6
        </score>
        <totalEpisodes>
            18集
        </totalEpisodes>
        <type>
            <label>剧情</label>
            <label>冒险</label>
            <label>武侠</label>
            <label>历史</label>
        </type>
        <startTime>
            <year>
                2008
            </year>
            <month>
                7
            </month>
            <day>
                17
            </day>
        </startTime>
        <anIntrodu>
            <![CDATA[ 该剧情前承第一部《秦时明月之百步飞剑》，后接第三部《秦时明月之诸子百家》，以墨家机关城守卫战为主线。讲述了墨家为守卫机关城与秦国和流沙对战的故事。]]>
        </anIntrodu>
    </animation>

    <animation id="A003">
        <animeName>
            秦时明月之诸子百家
        </animeName>
        <animeMaker>
            杭州玄机科技信息有限公司
        </animeMaker>
        <ref platform="腾讯视频">
            https://v.qq.com/x/cover/mzc002001kt6n30/y003386ac6j.html
        </ref>
        <director>
            <name>沈乐平</name>
        </director>
        <screenwriter>
            <name>沈乐平</name>
        </screenwriter>
        <origin_author>
            <name>
                温世仁
            </name>
        </origin_author>
        <releasePlace>
            中国
        </releasePlace>
        <language>
            汉语
        </language>
        <duration>
            22分钟/集
        </duration>
        <score site="腾讯视频">
            7.6
        </score>
        <totalEpisodes>
            34集
        </totalEpisodes>
        <type>
            <label>剧情</label>
            <label>冒险</label>
            <label>武侠</label>
            <label>历史</label>
        </type>
        <startTime>
            <year>
                2010
            </year>
            <month>
                6
            </month>
            <day>
                10
            </day>
        </startTime>
        <anIntrodu>
            <![CDATA[ 公元前222年，秦发兵六十万攻楚，楚军节节败退。乱军之中，日后的名将之星蒙恬（蒙武之子）与未来的西楚霸王少羽第一次在沙场相遇。
            楚军寡不敌众，情况危急万分，少年霸王与帝国将星的初次交锋，胜负难测……
            两年之后，秦灭六国，统一中国，秦始皇成为中国历史上第一位皇帝。然而，乱世并未结束，一股强大的力量正在为颠覆大秦而崛起。
            墨家、儒家、道家、法家、兵家、纵横家、阴阳家、农家、名家等，历史上称之为诸子百家。他们有的集结六国残余势力，为推翻帝国保证伺机而动；有的追随帝国主人的脚步，希望在这片大地上创立一个宇内光耀千秋万代的辉煌国度；亦有的借帝国的庞大势力，逐步实现自己不为人知的目的……
            如今，天下反秦势力最后的堡垒——墨家机关城，正遭遇三百年来最大的一次危机……
            盗跖虽然成功脱出，赶往求援，却被一神秘少女拦住去路。与此同时，墨家巨子率领各家英雄在赶往机关城途中，也遭到了阴阳家高手出其不意的暗袭。
            机关城中，身中剑伤的盖聂挥剑斩向身后……
            十年后，纵与横再次交锋，鬼谷的宿命之战，终将在此有一个了结！
            墨家机关城会否就此陷落？墨家众人的命运将何去何从？
            天明的面前究竟还有多少荆棘之路在等待着他？
            被阴阳家虏去的高月又会有何遭遇？
            要以孤家寡人对抗诸子百家，嬴政能有几分胜算？
            在这动荡的乱世中，谁才能成为真正的王者？
            ……
            我们的故事，这仅只是开始！]]>
        </anIntrodu>
    </animation>

    <animation id="A004">
        <animeName>
            秦时明月之万里长城
        </animeName>
        <animeMaker>
            杭州玄机科技信息有限公司
        </animeMaker>
        <ref platform="腾讯视频">
            https://v.qq.com/x/cover/mzc002001kt6n30/l0033aqffz1.html
        </ref>
        <director>
            <name>沈乐平</name>
        </director>
        <screenwriter>
            <name>沈乐平</name>
        </screenwriter>
        <origin_author>
            <name>
                温世仁
            </name>
        </origin_author>
        <releasePlace>
            中国
        </releasePlace>
        <language>
            汉语
        </language>
        <duration>
            22分钟/集
        </duration>
        <score site="腾讯视频">
            7.6
        </score>
        <totalEpisodes>
            37集
        </totalEpisodes>
        <type>
            <label>剧情</label>
            <label>冒险</label>
            <label>武侠</label>
            <label>历史</label>
        </type>
        <startTime>
            <year>
                2012
            </year>
            <month>
                9
            </month>
            <day>
                30
            </day>
        </startTime>
        <anIntrodu>
            <![CDATA[自从机关城崩毁，墨家抵抗势力几乎被全部清除。秦帝国又回到了太平盛世的迷梦中。
            咸阳宫中的嬴政一边动用无数劳工营造万里长城，一边进行着一些更为机密的计划，现在，这个计划已经接近完成，由阴阳家协助完成的巨艇“蜃楼”已经建造完毕。它壮丽精绝的身姿浮现海平线彼端，宛如人人梦想中的海上仙山。它究竟蕴藏着什么秘密？它最终将要航向何处，为了解开这些疑团，各家各派势力慢慢汇集到这座平静的海边小城。天明和少羽此时为了避开秦兵的追捕，正在儒家庄园生活和学习。而接下来各种奇异事件次第发生，小城的平静也被完全打破。
            假扮为客商的秦军小队全军覆没，护送的货物下落不明。神秘高手联袂侵入将军府，天机楼内收藏的重要宝物竟然不翼而飞。寡言少语的少女石兰，武功高强的剑客卫庄，妩媚妖娆的妖女赤练，都纷纷展现出性格的另一面，谁是敌人，谁是朋友，再难分辨。
            桑海城，暗流涌动。天明——背负神秘身世的少年。盖聂——百步飞剑独步天下的剑圣。少羽——楚国项氏唯一的传人。仇敌与伙伴们，都深深卷入这时代的飓风里。风起，自蜃楼装饰古雅的舱室空隙滑过，徘徊于秦廷雄壮的梁柱间。在丞相李斯的唇角，在将军蒙恬的剑尖，在少女高月的眼眸，在智圣张良的眉间。它掠过挥汗如雨的长城工地，切入黄金骑兵的军阵边缘。在天下百姓的私语中，万千关城的旌旗间，它似乎无所不在。所有的生死仇，家国恨，都将在那个时刻凝结。所有人的目光，都将在那个地点汇集 。]]>
        </anIntrodu>
    </animation>

    <animation id="A005">
        <animeName>
            秦时明月之君临天下
        </animeName>
        <animeMaker>
            杭州玄机科技信息有限公司
        </animeMaker>
        <ref platform="腾讯视频">
            https://v.youku.com/v_show/id_XODU2MTEyNjI4.html
        </ref>
        <director>
            <name>沈乐平</name>
        </director>
        <screenwriter>
            <name>沈乐平</name>
        </screenwriter>
        <origin_author>
            <name>
                温世仁
            </name>
        </origin_author>
        <releasePlace>
            中国
        </releasePlace>
        <language>
            汉语
        </language>
        <duration>
            22分钟/集
        </duration>
        <score site="优酷">
            9.8
        </score>
        <totalEpisodes>
            75集
        </totalEpisodes>
        <type>
            <label>剧情</label>
            <label>冒险</label>
            <label>武侠</label>
            <label>历史</label>
        </type>
        <startTime>
            <year>
                2014
            </year>
            <month>
                12
            </month>
            <day>
                25
            </day>
        </startTime>
        <anIntrodu>
            <![CDATA[ 为躲避公输家族霸道机关兽的追杀，天明、少羽、石兰三人误打误撞，登上了停泊在海边的蜃楼。这艘始终停留在远处，可望而不可即的神秘巨舰，终于第一次近距离展现在三人面前，它华丽的外表之下，隐藏着天大的秘密。为躲开蜃楼上阴阳家弟子的追捕，三人逐渐深入到这座谜城一般的巨舰内部，开始了奇幻莫测的探险逃亡之旅。
            与此同时，庖丁顺利从秦军监狱脱逃，并为墨家众人带回了重要信息，张良连夜制定出了第一步行动计划，青龙计划由此缓缓拉开序幕。
            蜃楼上，天明等人迷失在奇异诡谲的无尽回廊之中，正在不知所措的时候，竟是高月的身影出现在远处。
            桑海城郊，扶苏公子在一次出巡途中，遭遇刺客伏击。李斯奉命追查谋逆真凶，却发现种种蛛丝马迹都将嫌疑的矛头指向了小圣贤庄。
            博浪沙前，风雨欲来，如利箭在弦，一触即发。而机缘巧合之下，天明和少羽却发现了更加令人震惊的秘密。
            风卷雨击里，历史默然转身，乱世的帷幕，砰然落下。他说这片土地上我才是君临天下的真正王者，而他们说，即使注定了这条道路铺满荆棘与鲜血，我们仍将继续前行。你的执念阻挡不住侠者通往光明的大道。谁才是最终掌握乾坤的那个人，这不是句点，仅只是又翻过了新的一页篇章。]]>
        </anIntrodu>
    </animation>

    <animation id="A006">
        <animeName>
            天行九歌
        </animeName>
        <animeMaker>
            杭州玄机科技信息有限公司
        </animeMaker>
        <ref platform="腾讯视频">
            https://v.qq.com/x/cover/mzc002001kt6n30/h0033lwsz5l.html
        </ref>
        <director>
            <name>沈乐平</name>
            <name>金蕾</name>
        </director>
        <screenwriter>
            <name>沈乐平</name>
        </screenwriter>
        <releasePlace>
            中国
        </releasePlace>
        <language>
            汉语
        </language>
        <duration>
            20分钟/集
        </duration>
        <score site="bilibili">
            9.7
        </score>
        <totalEpisodes>
            90集
        </totalEpisodes>
        <type>
            <label>剧情</label>
            <label>冒险</label>
            <label>玄幻</label>
            <label>历史</label>
        </type>
        <startTime>
            <year>
                2016
            </year>
            <month>
                3
            </month>
            <day>
                10
            </day>
        </startTime>
        <anIntrodu>
